version: '2'
services:
  elasticsearch:
    build: elasticsearch
    volumes:
      - "./elasticsearch/config:/usr/share/elasticsearch/config"
      - "./snapshots:/var/lib/elasticsearch/snapshots"
    env_file:
      - aws.env
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
